services:
  football-calendar:
    container_name: football-calendar
    image: ghcr.io/francisjgarcia/football-calendar:local
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.local
    env_file:
      - .env
      - ../src/.env
    volumes:
      - ../src:/app
      - ../tests:/app/tests
    user: root
    tty: true
    command: /bin/sh
    restart: on-failure
